spring.application.name=OpenWeatherAPI
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#SQL Configuration
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081